packages:
  - "packages/*"
catalogs:
  vite-vue:
    "vue": "3.3.13"
    "@vitejs/plugin-vue": "^5.2.4"
    "@vue/tsconfig": "0.6.0"
    "typescript": "~5.8.3"
    "vite": "^6.3.5"
    "vue-tsc": "^2.2.10"
  styles:
    "@tailwindcss/vite": "^4.1.5"
    "tailwindcss": "^4.1.5"
