packages:
  - "packages/*"
catalogs:
  vite-vue:
    "vue": "3.3.13"
    "@vitejs/plugin-vue": "^6.0.0"
    "@vue/tsconfig": "0.6.0"
    "typescript": "~5.8.3"
    "vite": "^7.0.6"
    "vue-tsc": "^3.0.4"
  styles:
    "@tailwindcss/vite": "^4.1.11"
    "tailwindcss": "^4.1.11"
