packages:
  - "packages/*"
catalogs:
  vite-vue:
    "vue": "3.3.13"
    "@vitejs/plugin-vue": "^5.2.3"
    "@vue/tsconfig": "0.6.0"
    "typescript": "~5.6.2"
    "vite": "^6.0.5"
    "vue-tsc": "^2.2.8"
  styles:
    "@tailwindcss/vite": "^4.0.17"
    "tailwindcss": "^4.0.17"
