packages:
  - "packages/*"
catalogs:
  vite-vue:
    "vue": "3.3.13"
    "@vitejs/plugin-vue": "^5.2.1"
    "@vue/tsconfig": "0.6.0"
    "typescript": "~5.6.2"
    "vite": "^6.0.5"
    "vue-tsc": "^2.2.0"
  styles:
    "autoprefixer": "^10.4.20"
    "postcss": "^8.4.49"
    "tailwindcss": "^3.4.17"
